services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'

  pedido-service:
    build: .
    ports:
      - "8080:8080"
  #   depends_on:
  #     - cliente-service
  #     - produto-service
  #     - pagamento-service
  
  # cliente-service:
  #   image: cliente-service:latest
  #   ports:
  #     - "8081:8080"

  # produto-service:
  #   image: produto-service:latest
  #   ports:
  #     - "8082:8080"

  # pagamento-service:
  #   image: pagamento-service:latest
  #   ports:
  #     - "8083:8080"

